# Site settings
title: Nelo | Freelance Web Developer & UI Designer
name: Aaron Noel De Leon
email: aaronnoeldeleon@gmail.com
description: I work remotely with startups and agencies around the world to transform ideas into great products for web and mobile.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://nelonoel.github.io" # the base hostname & protocol for your site
twitter_username: nelonoel
github_username:  nelonoel
contact_no: +632 916 837 5550

# Build settings
markdown: kramdown
permalink: /:title