---
title: Nelo | Web Developer & UI Designer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
available: false
name: Aaron Noel De Leon
email: hello@nelo.ph
description: I work remotely with startups and agencies around the world to transform
  ideas into great products for web and mobile.
baseurl: "/"
port: 1515
url: http://nelonoel.github.io
twitter_username: nelonoel
github_username: nelonoel
contact_no: "+632 916 837 5550"
markdown: kramdown
permalink: "/:title"
